name: Weapon Detector

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y.%m.%d/%H.%M')" >> $GITHUB_ENV

      - name: Build
        run: make build_linux

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist
          name: Weapon Detector - ${{ env.date_today }}
          tag_name: d/${{ env.date_today }}
